#! /bin/bash

echo 'removing home ivy 2 bloom common'
rm -r ~/.ivy2/cache/org.grails.plugins/bloom-common;

echo 'removing home ivy 2 bloom domain'
rm -r ~/.ivy2/cache/org.grails.plugins/bloom-domain;
