#! /bin/bash

export DOCKER_HOST=tcp://localhost:4243

for i in {49000..49900}; do
  
  x=$((i % 100));
  
  if [ "$x" -eq "0" ] 
  then
    echo "On $i"
  fi

  VBoxManage modifyvm "boot2docker-vm" --natpf1 delete "tcp-port$i,tcp,,$i,,$i";
  VBoxManage modifyvm "boot2docker-vm" --natpf1 delete "udp-port$i,udp,,$i,,$i";
done
