#! /bin/bash

export DOCKER_HOST=tcp://localhost:4243

for i in {49000..49999}; do
  
  x=$((i % 100));
  
  if [ "$x" -eq "0" ] 
  then
    echo "On $i"
  fi

  VBoxManage modifyvm "boot2docker-vm" --natpf1 "tcp-port$i,tcp,,$i,,$i";
  VBoxManage modifyvm "boot2docker-vm" --natpf1 "udp-port$i,udp,,$i,,$i";
done
