#! /bin/bash

boot2docker halt

for i in {49000..49999}; do
  
  x=$((i % 100));
  
  if [ "$x" -eq "0" ] 
  then
    echo "On $i"
  fi

  VBoxManage modifyvm "boot2docker-vm" --natpf1 delete "tcp-port$i";
  VBoxManage modifyvm "boot2docker-vm" --natpf1 delete "udp-port$i";
done
