#! /bin/bash

VBoxManage controlvm $1 acpipowerbutton || true

for i in $(eval echo {$2..$3}); do

  x=$((i % 100));

  if [ "$x" -eq "0" ]
  then
    echo "On $i"
  fi

  VBoxManage modifyvm "$1" --natpf1 "tcp-port$i,tcp,,$i,,$i";
  VBoxManage modifyvm "$1" --natpf1 "udp-port$i,udp,,$i,,$i";
done
