#! /bin/bash

tmux has-session -t zeo-server-dev
if [ $? != 0 ]
then
	tmux new-session -s zeo-server-dev -n grails-dev -d
	tmux send-keys -t zeo-server-dev 'cdw zeo_server' C-m
	tmux send-keys -t zeo-server-dev 'grails' C-m
	
	tmux split-window -v -t zeo-server-dev
	tmux send-keys -t zeo-server-dev 'cdw zeo_server' C-m

	tmux split-window -h -t zeo-server-dev:1.1
	tmux send-keys -t zeo-server-dev 'cdw zeo_server' C-m
	tmux send-keys -t zeo-server-dev 'docker/postgresql/run.sh' C-m
	tmux send-keys -t zeo-server-dev 'grails run-app' C-m

	tmux split-window -v -t zeo-server-dev
	tmux send-keys -t zeo-server-dev 'cdw zeo_server' C-m
	tmux send-keys -t zeo-server-dev 'guard -G ../zeoServer.guardFile' C-m

	tmux select-window -t zeo-server-dev:1
fi
tmux attach -t zeo-server-dev